Basic challenges
avolovplesk/php_course pull request #1
Opened 2022-06-21 10:45 UTC by avolovplesk

2022-06-21 16:59 UTC, ova777 requested changes

2022-06-21 16:59 UTC, ova777 commented on 1_binarySum/binarySum.php
> +function binarySum($one,$two): string
1. Если взялся указывать типы, то указывай их и для аргументов (в данном случае `string $one, string $two`)
2. После пробела не хватает запятой
3. Это также относится ко всем остальным заданиям, проверь пожалуйста везде

2022-06-21 16:59 UTC, ova777 commented on 1_binarySum/binarySum.php
> +    return "Result is: $binSum\n";
Результат должен быть бинарным числом в виде строки, т.е. например "1011", а не "Result is: 1011\n"

2022-06-21 16:59 UTC, ova777 commented on 2_isPowerOfThree/isPowerOfThree.php
> +    $exp = log((int) $number, 3);
Про то как писать type casting - с пробелом или без (`(int) $smth` vs `(int)$smth`) в PSR явных указаний нет, но все же предпочтительнее запись без пробела... можно сказать это что-то одно целое - "скастинная" переменная.
Поэтому если решишь оставить с пробелом - ок, будем считать что в твоем проекте принято так, но, например в Plesk-core сейчас пишут без пробела (а давно писали с пробелом).

2022-06-21 16:59 UTC, ova777 commented on 2_isPowerOfThree/isPowerOfThree.php
> +function isPowerOfThree($number): string
В данном задании предполагается что функция должна возвращать bool

2022-06-21 16:59 UTC, ova777 commented on 2_isPowerOfThree/isPowerOfThree.php
> +    if ( ! ctype_digit(strval($exp)) ) {
1. `!` не нужно выделять пробелами
2. Перед последней `)` лишний пробел

2022-06-21 16:59 UTC, ova777 commented on 2_isPowerOfThree/isPowerOfThree.php
> +    if ( ! ctype_digit(strval($exp)) ) {
Вместо strval лучше сделать type casting используя string: `(string)$exp`. Во-первых это более современный подход, во-вторых это быстрее работает, т.к. strval - это вызов функции, а любой дополнительный вызов функции - это дополнительное время.

2022-06-21 16:59 UTC, ova777 commented on 3_fib/fib.php
> +function fib($num): string
По заданию предполагается что функция будет возвращать именно найденное число (int)

2022-06-21 16:59 UTC, ova777 commented on 3_fib/fib.php
> +    $seq = [0,1];
После запятой не хватает пробела

2022-06-21 16:59 UTC, ova777 commented on 3_fib/fib.php
> +                $seq[] = $seq[$i - 1] + $seq[$i - 2];
На этой строке (и строке ниже) лишний отступ в 4 пробела

2022-06-21 16:59 UTC, ova777 commented on 4_addDigits/addDigits.php
> +
Лишний перевод строки

2022-06-21 16:59 UTC, ova777 commented on 4_addDigits/addDigits.php
> +function addDigits($num): string
По заданию функция должна вернуть "другое число", а не строку

2022-06-21 16:59 UTC, ova777 commented on 5_isBalanced/isBalanced.php
> +function isBalanced($str): string
По заданию предполагается что функция должна возвращать bool

2022-06-21 16:59 UTC, ova777 commented on 5_isBalanced/isBalanced.php
> +        } elseif ($str[$len - 1] === '(') {
Здесь лишний отступ слева

2022-06-21 16:59 UTC, ova777 commented on 6_isPerfect/isPerfect.php
> +function isPerfect($num): string
В задании указано что функция должна возвращать true или false (в общем bool)

2022-06-21 16:59 UTC, ova777 commented on 7_isHappy/isHappy.php
> +function isHappy($ticket): string
По заданию предполагается что функция должна возвращать bool

2022-06-21 16:59 UTC, ova777 commented on 8_fizzBuzz/fizzBuzz.php
> +function fizzBuzz($begin, $end)
В случае если функция ничего не возвращает - нужно указать `: void`

2022-06-21 16:59 UTC, ova777 commented on 8_fizzBuzz/fizzBuzz.php
> +        if ($i % 3 === 0 && $i & 5 === 0) {
Возможно ты хотел написать `$i % 5`, а не бинарную операцию?

2022-06-21 16:59 UTC, ova777 commented on 8_fizzBuzz/fizzBuzz.php
> +    return print_r("$result\n");
print_r (если у него не указан второй аргумент) печатает данные в stdout и возвращает true, соответственно ты делаешь `return true`, а функция ничего не должна возвращать

2022-06-22 08:46 UTC, ova777 requested changes

2022-06-22 08:46 UTC, ovaunit commented on 1_binarySum/binarySum.php
> +    return "$binSum\n";
Уже лучше, но тут ты возвращаешь не только результат, но и перевод строки. Достаточно вернуть только $binSum.

2022-06-22 08:46 UTC, ova777 commented on 2_isPowerOfThree/isPowerOfThree.php
> +    if ( !ctype_digit((string)$exp)) {
Перед восклицательным знаком не нужен пробел

2022-06-22 08:46 UTC, ova777 commented on 2_isPowerOfThree/isPowerOfThree.php
> +    if ( !ctype_digit((string)$exp)) {
И еще здесь можно пооптимизировать и совсем избавиться от конструкции if-else.
Выражение `!ctype_digit((string)$exp)` у тебя принимает значение true или false, а возвращаешь ты false или true.
Так почему бы сразу не возвращать результат этого выражения?

2022-06-22 08:46 UTC, ova777 commented on 5_isBalanced/isBalanced.php
> +    if ($amount !== 0) {
Здесь вместо условной конструкции можно сразу возвращать результат выражения `$amount === 0`

2022-06-22 08:46 UTC, ovaunit commented on 6_isPerfect/isPerfect.php
> +    if ($sum === $num) {
Здесь вместо условной конструкции можно сразу возвращать результат выражения `$sum === $num`

2022-06-22 08:46 UTC, ova777 commented on 7_isHappy/isHappy.php
> +        $sumFirst .= $ticket[$i];
Ты точно хотел здесь сделать конкатенацию (`.=`), а не суммирование (`+=`)?

2022-06-22 09:56 UTC, ova777 approved these changes

2022-06-22 09:56 UTC, merged